version: "3.8"

services:
  db:
    container_name: postgresql
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: taskmedia
      POSTGRES_DB: nucentral
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@task.media
      PGADMIN_DEFAULT_PASSWORD: taskmedia
    ports:
      - "8082:80"
